version: '3'

services:
  # karya-root:
  #   build: .
  #   image: karya-root
  #   container_name: karya-root
  # volumes:
  #   - .:/usr/src/karya
  # command: npx lerna run build

  karya-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: karya-backend
    depends_on:
      # - karya-root
      - karya-backend-db
      - karya-backend-redis
      - keycloak
    volumes:
      - .:/usr/src/karya
    ports:
      - 5000:5000
    command: node dist/Server.js

  karya-box:
    build:
      context: .
      dockerfile: ./box/Dockerfile
    image: karya-box
    depends_on:
      # - karya-root
      - karya-box-db
    volumes:
      - .:/usr/src/karya
    ports:
      - 8000:8000
    command: node dist/Server.js

  karya-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: karya-frontend
    depends_on:
      # - karya-root
      - karya-backend
    volumes:
      - .:/usr/src/karya
    ports:
      - 3000:3000
    command: serve -s build/ -l 3000

  karya-backend-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=karya
      - POSTGRES_USER=karya
      - POSTGRES_PASSWORD=karya

  karya-box-db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=box
      - POSTGRES_USER=karya
      - POSTGRES_PASSWORD=karya

  karya-backend-redis:
    image: redis
    ports:
      - 6379:6379

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
